---
# tasks file for nrser.homebrew
#
# installs homebrew

- name: try to run brew list
  command: brew list
  ignore_errors: true
  register: homebrew_brew_list

- name: set homebrew_installed fact from brew list return code
  set_fact:
    homebrew_installed: "{{ homebrew_brew_list.rc == 0 }}"

- name: install homebrew
  command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not homebrew_installed

- name: update homebrew itself and all formulas
  command: brew update
  